Microsoft/AzureBot

AzureBot/AzureBot.csproj
AzureBot/Web.config
AzureBot/packages.config

Update Microsoft.Bot.Builder NuGet package to [version 1.2.3.0](https://github.com/Microsoft/BotBuilder/releases/tag/NuGet1.2.3.0)

Update Microsoft.Bot.Builder NuGet package to latest version

---

AzureBot.Azure.Management/ResourceManagement/AzureRepository.cs
AzureBot/AzureBot.csproj
AzureBot/Dialogs/ActionDialog.cs
AzureBot/Forms/EntityForms.cs
AzureBot/Forms/Operations.cs
AzureBot/Helpers/VirtualMachineHelper.cs

- Add Shutdown command which will Power Off a VM (the vm will still incur compute charges)
- Repurpose Stop command which will Deallocate a VM (the vm won't incur compute charges but the IPs will be deleted)
- Update Help message to reflect the purpose of the Shutdown/Stop commands.

Add support for deallocating a VM. Close #13

---

AzureBot/AzureBot.csproj
AzureBot/Dialogs/ActionDialog.cs
AzureBot/Web.config
AzureBot/packages.config

Update to [version 0.1.1](https://www.nuget.org/packages/AuthBot/0.1.1-alpha)

Update AuthBot NuGet package. Close #22

---

AzureBot/Dialogs/ActionDialog.cs

Start runbook now recognizes the runbook name.

---

AzureBot.Azure.Management/Models/VirtualMachine.cs
AzureBot.Azure.Management/ResourceManagement/AzureRepository.cs
AzureBot/Dialogs/ActionDialog.cs
AzureBot/Forms/EntityForms.cs

Update VMs list to show resource group and size

---

AzureBot.Azure.Management/AzureBot.Azure.Management.csproj
AzureBot.Azure.Management/app.config
AzureBot.Azure.Management/packages.config
AzureBot/AzureBot.csproj
AzureBot/Web.config
AzureBot/packages.config

https://github.com/Microsoft/BotBuilder/releases/tag/NuGet1.2.4.0

Update Microsoft.Bot.Builder NuGet package to 1.2.4

---

AzureBot.Azure.Management/ResourceManagement/AzureRepository.cs
AzureBot/Dialogs/ActionDialog.cs

- Add logic to list automation accounts
- Update help message

List automation accounts

---

AzureBot/Dialogs/ActionDialog.cs
AzureBot/Forms/EntityForms.cs
AzureBot/Forms/RunbookParameterFormState.cs

Handle optional runbook parameters (Issue #44)

---

AzureBot.Azure.Management/ResourceManagement/AzureRepository.cs
AzureBot/Dialogs/ActionDialog.cs

Do not merge until #48 and #50 are merged; since I need to add the suggested messages in #43

Support for showing the description of a runbook. Issue #43

---

AzureBot.Azure.Management/ResourceManagement/AzureRepository.cs
AzureBot/Dialogs/ActionDialog.cs

Start runbook only list runbooks in Published state (Issue #31)

---

AzureBot/AzureBot.csproj
AzureBot/Dialogs/ActionDialog.cs
AzureBot/Dialogs/DialogExtensions.cs
AzureBot/Forms/AllVirtualMachinesFormState.cs
AzureBot/Forms/EntityForms.cs

Per Issue #35. Also Code refactoring to avoid duplicate code.

Support for starting/shutting down/stopping all VMs (Issue #35)

---

AzureBot.Azure.Management/Models/RunBook.cs
AzureBot.Azure.Management/ResourceManagement/AzureRepository.cs
AzureBot/Dialogs/ActionDialog.cs
AzureBot/Forms/EntityForms.cs

Show runbook state in List runbooks (Issue #48)
- Fix issue when trying to start a runbook not published (Issue #55)

Show runbook state in List runbooks and fix start not published runbook issue

---

AzureBot.ConsoleConversation/App.config
AzureBot.ConsoleConversation/Program.cs
AzureBot.Tests/BotHelper.cs
AzureBot.Tests/General.cs
AzureBot.Tests/azurebottests.runsettings
AzureBot/AzureBot.csproj
AzureBot/ContextConstants.cs
AzureBot/ContextExtensions.cs
AzureBot/Controllers/MessagesController.cs
AzureBot/Dialogs/ActionDialog.cs
AzureBot/Dialogs/DialogExtensions.cs
AzureBot/Global.asax.cs
AzureBot/Web.config
AzureBot/packages.config

Message Controler now handles async activity. This won't build yet as dependencies on AuthoBot still remains, needs to test basic commands, and needs to update command line and test projects.

New branch for updated Bot Framework V3

---

AzureBot.ConsoleConversation/App.config
AzureBot.ConsoleConversation/AzureBot.ConsoleConversation.csproj
AzureBot.ConsoleConversation/Program.cs
AzureBot.ConsoleConversation/packages.config
AzureBot.Tests/AzureBot.Tests.csproj
AzureBot.Tests/BotHelper.cs
AzureBot.Tests/General.cs
AzureBot.Tests/azurebottests.runsettings
AzureBot.Tests/packages.config

Updated with latest DirectLine nuget package version and small fixes to support

Updates to console app and tests

---

AzureBot.Tests/azurebottests.runsettings

Fixing testrunsettings - 'name' instead of 'key'

Fixing testrunsettings

---

AzureBot.Tests/AzureBot.Tests.csproj
AzureBot.Tests/General.cs
AzureBot.Tests/app.config
AzureBot.Tests/azurebottests.runsettings
AzureBot.Tests/packages.config

Updated Newtonsoft.Json, this seems to have fixed issues with the TestContext being null in AssemblyInitialize method

Updated to .NET 4.6 and Newtonsoft.Json

---

docs/CreateAzureADforAzureBot.md

* Map values to web.config developer guide
* Add new callback URL for multitenant app config

Update AzureAD Setup Guide

---

AzureBot/Web.config

fixes issues with server requests and server response time now showing up in app insights

Enable App Insights Web tracking

---

AzureBot/AzureBot.csproj
AzureBot/Dialogs/ActionDialog.cs
AzureBot/Dialogs/DialogExtensions.cs
AzureBot/Web.config
AzureBot/packages.config

Updated to latest Authbot and its dependencies; tested with VM and Runbook paths using emulator

Updating Authbot and its dependencies to the latest

---

_config.yml
index.md

Set theme jekyll-theme-merlot and migrate Page Generator content
